server:
  port: 8083

spring:
  application:
    name: dsa-service
  datasource:
    url: jdbc:postgresql://localhost:5440/byteascend_db
    username: admin
    password: adminpassword
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    table: flyway_schema_history_dsa
