server:
  port: 8082

spring:
  application:
    name: lms-service
  datasource:
    url: jdbc:postgresql://localhost:5432/byteascend_db
    username: admin
    password: adminpassword
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
